export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        REFRESH: '/auth/refresh',
        LOGOUT: '/auth/logout',
        ME: '/auth/me',
        RECOVER_PASSWORD: '/auth/recover-password',
        RECOVER_PASSWORD_VALIDATE: '/auth/recover-password/validate',
        RECOVER_RESET_PASSWORD: '/auth/recover-password/reset',
    },
    STUDENT: {
        GET: '/students',
        GET_BY_ID: (id: string) => `/students/${id}`,
        CREATE: '/students/create',
        UPDATE: (id: string) => `/students/update/${id}`,
        DELETE: (id: string) => `/students/delete/${id}`,
        GET_TYPEAHEAD: '/students/typeahead',
        ME: '/students/me',
    },
    PROFESSOR: {
        GET: '/professors',
        CREATE: '/professors/create',
        UPDATE: (id: string) => `/professors/update/${id}`,
        DELETE: (id: string) => `/professors/delete/${id}`,
        GET_TYPEAHEAD: '/professors/typeahead',
        ME: '/professors/me',
    },
    COMPANY_MENTOR: {
        GET: '/company-mentors',
        CREATE: '/company-mentors/create',
        UPDATE: (id: string) => `/company-mentors/update/${id}`,
        DELETE: (id: string) => `/company-mentors/delete/${id}`,
        GET_TYPEAHEAD: '/company-mentors/typeahead',
    },
    FACULTY: {
        GET: '/faculty',
        GET_TYPEAHEAD: '/faculty/typeahead',
        CREATE: '/faculty/create',
        UPDATE: (id: string) => `/faculty/update/${id}`,
        DELETE: (id: string) => `/faculty/delete/${id}`,
    },
    ACADEMIC_PROGRAM: {
        GET: '/academic-programs',
        CREATE: '/academic-programs/create',
        UPDATE: (id: string) => `/academic-programs/update/${id}`,
        DELETE: (id: string) => `/academic-programs/delete/${id}`,
        GET_TYPEAHEAD: '/academic-programs/typeahead',
    },
    COMPANY: {
        GET: '/companies',
        GET_BY_ID: (id: string) => `/companies/${id}`,
        CREATE: '/companies/create',
        UPDATE: (id: string) => `/companies/update/${id}`,
        UPDATE_LOGO: (id: string) => `/companies/update-logo/${id}`,
        DELETE: (id: string) => `/companies/delete/${id}`,
        GET_TYPEAHEAD: '/companies/typeahead',
        CREATE_CONTRACT: (companyId: string) => `/companies/${companyId}/contracts`,
        GET_CONTRACTS: (companyId: string) => `/companies/${companyId}/contracts`,
        UPDATE_CONTRACT: (contractId: string) => `/companies/contracts/${contractId}`,
        DELETE_CONTRACT: (id: string) => `/companies/contracts/${id}`,
    },
    COUNTRY: {
        GET: '/country',
        CREATE: '/country/create',
        UPDATE: (id: string) => `/country/update/${id}`,
        DELETE: (id: string) => `/country/delete/${id}`,
        GET_TYPEAHEAD: '/country/typeahead',
    },
    CITY: {
        GET: '/city',
        CREATE: '/city/create',
        UPDATE: (id: string) => `/city/update/${id}`,
        DELETE: (id: string) => `/city/delete/${id}`,
        GET_TYPEAHEAD: '/city/typeahead',
    },
    STUDENT_COMPANY_LINKING_PROCESS: {
        GET: '/student-company-linking-processes',
        CREATE: '/student-company-linking-processes/create',
        UPDATE_STATUS: (id: string) => `/student-company-linking-processes/update/${id}/status`,
        DELETE: (id: string) => `/student-company-linking-processes/delete/${id}`,
    },
    NEWS: {
        GET: '/news',
        GET_BY_ID: (id: string) => `/news/${id}`,
        CREATE: '/news/create',
        UPDATE: (id: string) => `/news/update/${id}`,
        DELETE: (id: string) => `/news/delete/${id}`,
    },
    STUDENT_COMPANY_CONTRACT: {
        GET: '/student-company-contracts',
        CREATE: '/student-company-contracts/create',
        DELETE: (id: string) => `/student-company-contracts/delete/${id}`,
        ACTIVATE: (id: string) => `/student-company-contracts/${id}/activate`,
        CANCEL: (id: string) => `/student-company-contracts/${id}/cancel`,
    },
    PRACTICE_TEMPLATE: {
        GET: '/practice-templates',
        CREATE: '/practice-templates/create',
        UPDATE: (id: string) => `/practice-templates/update/${id}`,
        DELETE: (id: string) => `/practice-templates/delete/${id}`,
        GET_TYPEAHEAD: '/practice-templates/typeahead',
        DELIVERABLES: {
            GET: (practiceTemplateId: string) => `/practice-templates/${practiceTemplateId}/deliverables`,
            CREATE: (practiceTemplateId: string) => `/practice-templates/${practiceTemplateId}/deliverables/create`,
            UPDATE: (practiceTemplateId: string, deliverableId: string) => `/practice-templates/${practiceTemplateId}/deliverables/update/${deliverableId}`,
            DELETE: (practiceTemplateId: string, deliverableId: string) => `/practice-templates/${practiceTemplateId}/deliverables/delete/${deliverableId}`,
        },
        FORMATS: {
            GET: (practiceTemplateId: string) => `/practice-templates/${practiceTemplateId}/formats`,
            CREATE: (practiceTemplateId: string) => `/practice-templates/${practiceTemplateId}/formats/create`,
            UPDATE: (practiceTemplateId: string, formatId: string) => `/practice-templates/${practiceTemplateId}/formats/update/${formatId}`,
            DELETE: (practiceTemplateId: string, formatId: string) => `/practice-templates/${practiceTemplateId}/formats/delete/${formatId}`,
        }
    },
    PRACTICE_DEFINITION: {
        GET: '/practice-definitions',
        CREATE: '/practice-definitions/create',
        UPDATE: (id: string) => `/practice-definitions/update/${id}`,
        DELETE: (id: string) => `/practice-definitions/delete/${id}`,
        GET_TYPEAHEAD: '/practice-definitions/typeahead',
    },
    PRACTICE_PROCESS: {
        GET: '/practice-processes',
        GET_BY_ID: (id: string) => `/practice-processes/${id}`,
        START: '/practice-processes/start',
        DELETE: (id: string) => `/practice-processes/delete/${id}`,
        CANCEL: (id: string) => `/practice-processes/${id}/cancel`,
        GET_STUDENT_CURRENT: '/practice-processes/student/me/current',
        GET_PROFESSOR_CURRENT: '/practice-processes/professor/me/current',
    },
    PRACTICE_PROCESS_DELIVERABLE: {
        SUBMIT: (practiceProcessId: string, deliverableId: string) => `/practice-processes/${practiceProcessId}/deliverables/${deliverableId}/submit`,
        GRADE: (practiceProcessId: string, deliverableId: string) => `/practice-processes/${practiceProcessId}/deliverables/${deliverableId}/grade`,
    },
};
