export enum FormFieldType {
    TEXT = 'text',
    NUMBER = 'number',
    PASSWORD = 'password',
    EMAIL = 'email',
    TYPEAHEAD = 'typeahead',
    SELECT = 'select',
    MULTISELECT = 'multiselect',
    OTP = 'otp',
    DATE = 'date',
    DATETIME_LOCAL = 'datetime-local',
    FILE = 'file',
    RICH_TEXT = 'rich-text',
    CHECKBOX = 'checkbox',
    TEXTAREA = 'textarea',
} 